# Project information
site_name: Cellar CRM Docs
site_url: https://tallescellar.github.io/docs-CellarCRM/

# Repository
repo_name: tallescellar/docs-CellarCRM
repo_url: https://github.com/tallescellar/docs-CellarCRM
edit_uri: ''

# Configuration
theme:
  name: material
  logo: assets/logo.png
  language: pt-BR
  features:
    - announce.dismiss
  custom_dir: overrides
  icon:
      repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: white
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Montserrat
    code: Roboto Mono

# Customization      
extra:
  version:
    provider: mike

nav:
    - 'Início': 'index.md'
    - 'Desenvolvimento':
          - 'Instalação': 'desenvolvimento/index.md'
          - 'Acessando o CRM': 'desenvolvimento/acesso.md'
          - 'Estrutura do Projeto': 'desenvolvimento/estrutura.md'          